/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jhonbustamante011501@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.AlreadyExist
import io.swagger.client.model.InvalidInput
import io.swagger.client.model.InventoryItem
import io.swagger.client.model.Manufacturer
import io.swagger.client.model.Modasd
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object AdminsApi {

  /**
   * Adds an item to the system
   * 
   * Expected answers:
   *   code 200 : Seq[Manufacturer] (search results matching criteria)
   *   code 201 : Seq[Modasd] (item created)
   *   code 400 : Seq[InvalidInput] (invalid input, object invalid)
   *   code 409 : Seq[AlreadyExist] (an existing item already exists)
   * 
   * @param inventoryItem Inventory item to add
   */
  def addInventory(inventoryItem: Option[InventoryItem] = None): ApiRequest[Seq[Manufacturer]] =
    ApiRequest[Seq[Manufacturer]](ApiMethods.POST, "https://virtserver.swaggerhub.com/kamotejhon/kamote/1.0.0", "/inventory", "application/json")
      .withBody(inventoryItem)
      .withSuccessResponse[Seq[Manufacturer]](200)
      .withErrorResponse[Seq[Modasd]](201)
      .withErrorResponse[Seq[InvalidInput]](400)
      .withErrorResponse[Seq[AlreadyExist]](409)
      

}

