/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jhonbustamante011501@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ModasdData (
  addedFriend: Option[String] = None,
  postedStatus: Option[String] = None,
  homepage: Option[String] = None,
  email: Option[String] = None
) extends ApiModel


